#include "timeline_anomaly.h"
#include "belya_harness.h" /* almaz_goals_add */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define ANOMALY_WINDOW_DAYS 7
#define ANOMALY_MIN_COUNT 5      /* too few events -> noise */
#define ANOMALY_SIGMA 3.0
#define ANOMALY_MAX_TYPES 64
#define ANOMALY_MAX_DAYS 64

typedef struct {
    char event_type[96];
    int counts_pos;   /* index into counts array below */
    double mean;
    double sigma;
} AnomalyTypeStat;

static int cmp_double(const void *a, const void *b) {
    double x = *(const double *)a;
    double y = *(const double *)b;
    return (x > y) - (x < y);
}

int timeline_anomaly_scan(BelyaAgent *agent) {
    if (!agent || !agent->db) return -1;

    sqlite3_stmt *stmt = NULL;
    const char *sql =
        "SELECT event_type, date(created_at) AS d, COUNT(*) "
        "FROM agent_timeline "
        "WHERE created_at >= datetime('now', '-7 days') "
        "GROUP BY event_type, d;";
    if (sqlite3_prepare_v2(agent->db, sql, -1, &stmt, NULL) != SQLITE_OK) {
        return -1;
    }

    char types[ANOMALY_MAX_TYPES][96];
    memset(types, 0, sizeof(types));
    double counts[ANOMALY_MAX_TYPES][ANOMALY_MAX_DAYS];
    int counts_n[ANOMALY_MAX_TYPES] = {0};
    int ntypes = 0;

    while (sqlite3_step(stmt) == SQLITE_ROW) {
        const char *type = (const char *)sqlite3_column_text(stmt, 0);
        int c = sqlite3_column_int(stmt, 2);
        if (!type || c <= 0) continue;
        int idx = -1;
        for (int i = 0; i < ntypes; i++) {
            if (types[i][0] != '\0' && strcmp(types[i], type) == 0) { idx = i; break; }
        }
        if (idx < 0 && ntypes < ANOMALY_MAX_TYPES) {
            idx = ntypes++;
            strncpy(types[idx], type, 95);
            types[idx][95] = '\0';
        }
        if (idx < 0) continue;
        if (counts_n[idx] < ANOMALY_MAX_DAYS) {
            counts[idx][counts_n[idx]++] = (double)c;
        } else {
            /* window full: replace oldest */
            counts[idx][0] = (double)c;
        }
    }
    sqlite3_finalize(stmt);

    int anomalies = 0;
    for (int i = 0; i < ntypes; i++) {
        int n = counts_n[i];
        if (n < 2) continue; /* need at least history + today */
        double sorted[ANOMALY_MAX_DAYS];
        memcpy(sorted, counts[i], (size_t)n * sizeof(double));
        qsort(sorted, (size_t)n, sizeof(double), cmp_double);
        double today_count = sorted[n - 1];
        double sum = 0.0;
        for (int j = 0; j < n - 1; j++) sum += sorted[j];
        double mean = sum / (double)(n - 1);
        double var = 0.0;
        for (int j = 0; j < n - 1; j++) {
            double d = sorted[j] - mean;
            var += d * d;
        }
        double sigma = (n - 1 > 1) ? sqrt(var / (double)(n - 2)) : 0.0;

        bool anomalous = sigma > 0.0 && today_count >= ANOMALY_MIN_COUNT &&
                         today_count > mean + ANOMALY_SIGMA * sigma;
        if (anomalous) {
            char summary[256];
            snprintf(summary, sizeof(summary),
                     "anomaly_detected: event_type=%.20s today=%d (7d mean=%.1f sigma=%.1f threshold=%.1f)",
                     types[i], (int)today_count, mean, sigma, mean + ANOMALY_SIGMA * sigma);
            belya_agent_log_timeline(agent, "anomaly_detected", summary);

            sqlite3_stmt *gstmt = NULL;
            int pending = 0;
            if (sqlite3_prepare_v2(agent->db,
                                   "SELECT COUNT(*) FROM agent_goals WHERE category='ANOMALY_REMEDIATION' AND status='pending';",
                                   -1, &gstmt, NULL) == SQLITE_OK && sqlite3_step(gstmt) == SQLITE_ROW) {
                pending = sqlite3_column_int(gstmt, 0);
            }
            sqlite3_finalize(gstmt);
            if (pending == 0) {
                char goal[320];
                snprintf(goal, sizeof(goal), "Investigate timeline anomaly: event_type=%.20s (today=%d > mean+3σ)", types[i], (int)today_count);
                almaz_goals_add(agent->db, goal, "ANOMALY_REMEDIATION", 70, "generated by timeline_anomaly_scan");
            }
            anomalies++;
        }
    }

    return anomalies;
}